language: node_js
node_js: node
cache:
  directories:
    - node_modules
install: npm install
before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start

script:
- npm run build
- npm run karma.single
- codecov -t ${CODECOV}
