language: node_js
node_js: node
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
install: npm install

# https://iamakulov.com/notes/install-google-chrome-on-travis/
addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
- npm run build
- npm run karma.single
- codecov -t ${CODECOV}
